import java.awt.Font
import javax.swing.table.DefaultTableModel
import java.awt.CardLayout
import javax.swing.*

/**
 *
 * @author shmue
 */
class FindSeferByNameJPanel : JPanel() {
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private fun initComponents() {
        buttonGroup1 = ButtonGroup()
        jLabel1 = JLabel()
        seferNameTextField = JTextField()
        jScrollPane1 = JScrollPane()
        table = JTable()
        jLabel2 = JLabel()
        searchModeExplanation = JPanel()
        jLabel6 = JLabel()
        exactSearchRadioButton = JRadioButton()
        rootWordSearchRadioButton = JRadioButton()
        similaritySearchRadioButton = JRadioButton()
        jLabel1!!.text = "Name of sefer:"
        table!!.autoCreateRowSorter = true
        table!!.font = Font("Tahoma", 0, 12) // NOI18N
        table!!.model = object : DefaultTableModel(
            arrayOf(
                arrayOf(null, null, null, null, null, null, null),
                arrayOf(null, null, null, null, null, null, null),
                arrayOf(null, null, null, null, null, null, null),
                arrayOf(null, null, null, null, null, null, null)
            ), arrayOf(
                "Shelf", "Name", "Author", "Publisher", "Volume", "Copies", "Category"
            )
        ) {
            var types = arrayOf(
                String::class.java,
                String::class.java,
                String::class.java,
                String::class.java,
                Any::class.java,
                String::class.java,
                String::class.java
            )
            var canEdit = booleanArrayOf(
                false, false, false, false, false, false, false
            )

            override fun getColumnClass(columnIndex: Int): Class<*> {
                return types[columnIndex]
            }

            override fun isCellEditable(rowIndex: Int, columnIndex: Int): Boolean {
                return canEdit[columnIndex]
            }
        }
        jScrollPane1!!.setViewportView(table)
        jLabel2!!.text = "Results:"
        searchModeExplanation!!.border = BorderFactory.createTitledBorder("Exact search")
        searchModeExplanation!!.toolTipText = ""
        searchModeExplanation!!.layout = CardLayout()
        jLabel6!!.text = "Search mode:"
        buttonGroup1!!.add(exactSearchRadioButton)
        exactSearchRadioButton!!.text = "Exact search"
        buttonGroup1!!.add(rootWordSearchRadioButton)
        rootWordSearchRadioButton!!.text = "Root word search"
        buttonGroup1!!.add(similaritySearchRadioButton)
        similaritySearchRadioButton!!.text = "Similarity search"
        var layout = GroupLayout(this)
        layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(
                                            searchModeExplanation,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addContainerGap()
                                )
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(jScrollPane1)
                                        .addContainerGap()
                                )
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                    layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(seferNameTextField)
                                                )
                                                .addGroup(
                                                    layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(0, 0, Short.MAX_VALUE.toInt())
                                                )
                                        )
                                        .addGap(6, 6, 6)
                                )
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exactSearchRadioButton)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rootWordSearchRadioButton)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(similaritySearchRadioButton)
                                        .addGap(0, 0, Short.MAX_VALUE.toInt())
                                )
                        )
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(exactSearchRadioButton)
                                .addComponent(rootWordSearchRadioButton)
                                .addComponent(similaritySearchRadioButton)
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchModeExplanation, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(
                                    seferNameTextField,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE.toInt())
                        .addContainerGap()
                )
        )
    } // </editor-fold>                        

    // Variables declaration - do not modify                     
    private var buttonGroup1: ButtonGroup? = null
    private var exactSearchRadioButton: JRadioButton? = null
    private var jLabel1: JLabel? = null
    private var jLabel2: JLabel? = null
    private var jLabel6: JLabel? = null
    private val jPanel6: JPanel? = null
    private val jPanel7: JPanel? = null
    private val jPanel9: JPanel? = null
    private val jRadioButton12: JRadioButton? = null
    private val jRadioButton13: JRadioButton? = null
    private val jRadioButton6: JRadioButton? = null
    private val jRadioButton7: JRadioButton? = null
    private val jRadioButton8: JRadioButton? = null
    private val jRadioButton9: JRadioButton? = null
    private var jScrollPane1: JScrollPane? = null
    private var rootWordSearchRadioButton: JRadioButton? = null
    private var searchModeExplanation: JPanel? = null
    private var seferNameTextField: JTextField? = null
    private var similaritySearchRadioButton: JRadioButton? = null
    private var table: JTable? = null // End of variables declaration                   

    /**
     * Creates new form FindSeferByName
     */
    init {
        initComponents()
    }
}