import javax.swing.GroupLayout
import javax.swing.JCheckBox
import javax.swing.JLabel
import javax.swing.JPanel
import javax.swing.LayoutStyle

/**
 *
 * @author shmuel
 */
class PlainTextExplanationJPanel(explanation: String, val matchWholeWordChangedCallback: (Boolean) -> Unit) : JPanel() {
    val boundaryCheckBox = JCheckBox("Only match whole words (\"חומש\" should not match \"חומשי\" or \"החומשים\")")
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param explanation
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private fun initComponents(explanation: String) {
        jLabel1 = JLabel()

        boundaryCheckBox.addItemListener {
            matchWholeWordChangedCallback(boundaryCheckBox.isSelected.also { println("Calling boundary callback: $it") })
        }
//        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1!!.text = "<html><body style='width: %1spx'>$explanation</body>"
        val jPanel5Layout = GroupLayout(this)
        layout = jPanel5Layout
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(
                            jLabel1,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addComponent(boundaryCheckBox)
                )
        )
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            jLabel1,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boundaryCheckBox)
                        .addContainerGap()
                )
        )
        /*
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );*/
    } // </editor-fold>                        

    // Variables declaration - do not modify                     
    private var jLabel1: JLabel? = null
    private val jPanel5: JPanel? = null // End of variables declaration                   

    /**
     * Creates new form ExactMatchJPanel
     */
    init {
        initComponents(explanation)
    }
}
