import java.awt.Component
import java.awt.event.ActionListener
import java.awt.event.ActionEvent
import javax.swing.*

/**
 *
 * @author shmuel
 */
class RootWordSearchExplanationJPanel1 : JPanel() {
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private fun initComponents() {
        jPanel5 = JPanel()
        jRadioButton6 = JRadioButton()
        jRadioButton7 = JRadioButton()
        jLabel1 = JLabel()
        jLabel2 = JLabel()
        jPanel16 = JPanel()
        jRadioButton28 = JRadioButton()
        jRadioButton29 = JRadioButton()
        jLabel3 = JLabel()
        jLabel4 = JLabel()
        jLabel5 = JLabel()
        jLabel6 = JLabel()
        jToggleButton1 = JToggleButton()
        jPanel5!!.border = BorderFactory.createTitledBorder("Search phrase interpretation")
        jRadioButton6!!.text = "Unordered/Keywords"
        jRadioButton6!!.addActionListener { evt -> jRadioButton6ActionPerformed(evt) }
        jRadioButton7!!.text = "Ordered/Sequential"
        jRadioButton7!!.addActionListener { evt -> jRadioButton7ActionPerformed(evt) }
        jLabel1!!.text =
            "Disregard the order that the words in the search phrase appear in, and return results which contain the shorashim that are in the search phrase, regardless of the order in which they appear in the result."
        jLabel2!!.text =
            "Respect the order that the words in the search phrase appear in, and only return results in which the shorashim appear in the same order as the order in which they appear in the search phrase."
        val jPanel5Layout = GroupLayout(jPanel5)
        jPanel5!!.layout = jPanel5Layout
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(
                                    jRadioButton6,
                                    GroupLayout.PREFERRED_SIZE,
                                    1297,
                                    GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                    jRadioButton7,
                                    GroupLayout.PREFERRED_SIZE,
                                    983,
                                    GroupLayout.PREFERRED_SIZE
                                )
                                .addGroup(
                                    jPanel5Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(
                                            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                    jLabel2,
                                                    GroupLayout.PREFERRED_SIZE,
                                                    1268,
                                                    GroupLayout.PREFERRED_SIZE
                                                )
                                                .addComponent(jLabel1)
                                        )
                                )
                        )
                        .addGap(0, 0, 0)
                )
        )
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton6, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                            LayoutStyle.ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap()
                )
        )
        jPanel16!!.border = BorderFactory.createTitledBorder("Search strictness")
        jRadioButton28!!.text = "Match all"
        jRadioButton28!!.addActionListener { evt -> jRadioButton28ActionPerformed(evt) }
        jRadioButton29!!.text = "Match any"
        jRadioButton29!!.addActionListener { evt -> jRadioButton29ActionPerformed(evt) }
        jLabel3!!.text = "Only return results which contain all of the shorashim contained in the search phrase."
        jLabel4!!.text = "Return results which contain any (even one) of the shorashim in the search phrase."
        val jPanel16Layout = GroupLayout(jPanel16)
        jPanel16!!.layout = jPanel16Layout
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    jPanel16Layout.createSequentialGroup()
                                        .addComponent(
                                            jRadioButton29,
                                            GroupLayout.PREFERRED_SIZE,
                                            983,
                                            GroupLayout.PREFERRED_SIZE
                                        )
                                        .addContainerGap()
                                )
                                .addGroup(
                                    jPanel16Layout.createSequentialGroup()
                                        .addComponent(
                                            jRadioButton28,
                                            GroupLayout.DEFAULT_SIZE,
                                            1291,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addContainerGap()
                                )
                                .addGroup(
                                    jPanel16Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(
                                            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                        )
                                        .addGap(0, 0, 0)
                                )
                        )
                )
        )
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton28, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(
                            LayoutStyle.ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addComponent(jRadioButton29)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap()
                )
        )
        jLabel5!!.text =
            "<html><body style='width: %1spx'>Root word search determines matching entries by comparing the root words contained in the search phrase with the root words in each catalog entry. Nouns are preserved in their full form (e.g. <font size=5> וּמִמַּאַמְרֵיהֶם</font> is reduced to <font size=5>מַאֲמָר</font> and not אמר), whereas verbs and adjectives are reduced to their root word. However, although the search engine may have a general understanding of dikduk, that does not make it a Talmid Chacham. For example, מאמרי can be read as <font size=5> מַאֲמָרֵי </font>or <font size=5>מֵאִמְרֵי</font>. The first reduces to מאמר and the second reduces to אמר, but without an understanding of the meaning and the context, not even a human would know how to properly punctuate it. </body>"
        jLabel6!!.text = "Search phrase shorashim: "
        jToggleButton1!!.text = "Show additional options"
        var layout = GroupLayout(this)
        layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(
                                            jPanel16,
                                            GroupLayout.Alignment.LEADING,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addComponent(
                                            jPanel5,
                                            GroupLayout.Alignment.LEADING,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE.toInt())
                                )
                                .addComponent(jToggleButton1)
                                .addComponent(jLabel6)
                        )
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE.toInt())
                )
        )
        layout.linkSize(SwingConstants.HORIZONTAL, *arrayOf<Component>(jPanel16!!, jPanel5!!))
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            jLabel5,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(
                            jPanel5,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(
                            jPanel16,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE
                        )
                        .addContainerGap()
                )
        )
    } // </editor-fold>                        

    private fun jRadioButton6ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    private fun jRadioButton7ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    private fun jRadioButton28ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    private fun jRadioButton29ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify                     
    private var jLabel1: JLabel? = null
    private var jLabel2: JLabel? = null
    private var jLabel3: JLabel? = null
    private var jLabel4: JLabel? = null
    private var jLabel5: JLabel? = null
    private var jLabel6: JLabel? = null
    private var jPanel16: JPanel? = null
    private var jPanel5: JPanel? = null
    private var jRadioButton28: JRadioButton? = null
    private var jRadioButton29: JRadioButton? = null
    private var jRadioButton6: JRadioButton? = null
    private var jRadioButton7: JRadioButton? = null
    private var jToggleButton1: JToggleButton? = null // End of variables declaration                   

    /**
     * Creates new form RootWordSearchExplanationJPanel
     */
    init {
        initComponents()
    }
}