import java.awt.EventQueue
import java.awt.event.ActionListener
import java.awt.event.ActionEvent
import javax.swing.*

/**
 *
 * @author shmuel
 */
class RootWordSearchSettingsJPanel(val searchableTableJPanel: SearchableTableJPanel) : JPanel() {
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private fun initComponents() {
        jPanel5 = JPanel()
        jRadioButton6 = JRadioButton()
        jRadioButton7 = JRadioButton()
        jLabel1 = JLabel()
        jLabel2 = JLabel()
        jPanel16 = JPanel()
        jRadioButton28 = JRadioButton()
        jRadioButton29 = JRadioButton()
        jLabel3 = JLabel()
        jLabel4 = JLabel()
        jPanel5!!.border = BorderFactory.createTitledBorder("Search phrase interpretation")
        jPanel16!!.border = BorderFactory.createTitledBorder("Search strictness")

        jRadioButton6!!.text = "Ordered/Sequential"
        jRadioButton7!!.text = "Unordered/Keywords"
        jRadioButton28!!.text = "Match all"
        jRadioButton29!!.text = "Match any"
        jRadioButton6!!.addActionListener {
            rootSearchShouldMatchSequential = true
            searchableTableJPanel.filterList()
        }
        jRadioButton7!!.addActionListener {
            rootSearchShouldMatchSequential = false
            searchableTableJPanel.filterList()
        }
        jRadioButton28!!.addActionListener {
            rootSearchShouldMatchAll = true
            searchableTableJPanel.filterList()
        }
        jRadioButton29!!.addActionListener {
            rootSearchShouldMatchAll = false
            searchableTableJPanel.filterList()
        }
        EventQueue.invokeLater {
            jRadioButton6!!.doClick()
        }
        EventQueue.invokeLater {
            jRadioButton28!!.doClick()
        }
        val buttonGroup1 = ButtonGroup()
        val buttonGroup2 = ButtonGroup()
        buttonGroup1.add(jRadioButton6)
        buttonGroup1.add(jRadioButton7)
        buttonGroup2.add(jRadioButton28)
        buttonGroup2.add(jRadioButton29)
        jLabel2!!.text =
            "Disregard the order that the words in the search phrase appear in, and return results which contain the shorashim that are in the search phrase, regardless of the order in which they appear in the result."
        jLabel1!!.text =
            "<html><body style='width: 1%spx'>Respect the order that the words in the search phrase appear in, and only return results in which the shorashim appear in the same order as the order in which they appear in the search phrase."
        jLabel3!!.text = "Only return results which contain all of the shorashim contained in the search phrase."
        jLabel4!!.text = "Return results which contain any (even one) of the shorashim in the search phrase."

        val jPanel5Layout = GroupLayout(jPanel5)
        jPanel5!!.layout = jPanel5Layout
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(
                                    jRadioButton6,
                                    GroupLayout.PREFERRED_SIZE,
                                    1297,
                                    GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                    jRadioButton7,
                                    GroupLayout.PREFERRED_SIZE,
                                    983,
                                    GroupLayout.PREFERRED_SIZE
                                )
                                .addGroup(
                                    jPanel5Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(
                                            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                    jLabel2,
                                                    GroupLayout.PREFERRED_SIZE,
                                                    1268,
                                                    GroupLayout.PREFERRED_SIZE
                                                )
                                                .addComponent(jLabel1)
                                        )
                                )
                        )
                        .addGap(0, 0, 0)
                )
        )
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton6, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                            LayoutStyle.ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap()
                )
        )
        val jPanel16Layout = GroupLayout(jPanel16)
        jPanel16!!.layout = jPanel16Layout
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    jPanel16Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(
                                            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                        )
                                )
                                .addGroup(
                                    jPanel16Layout.createSequentialGroup()
                                        .addGroup(
                                            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                    jRadioButton29,
                                                    GroupLayout.PREFERRED_SIZE,
                                                    983,
                                                    GroupLayout.PREFERRED_SIZE
                                                )
                                                .addComponent(
                                                    jRadioButton28,
                                                    GroupLayout.DEFAULT_SIZE,
                                                    GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE.toInt()
                                                )
                                        )
                                        .addContainerGap()
                                )
                        )
                )
        )
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton28, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(
                            LayoutStyle.ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addComponent(jRadioButton29)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap()
                )
        )
        val layout = GroupLayout(this)
        this.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 1327, Short.MAX_VALUE.toInt())
                .addGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                    layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(
                                            jPanel16,
                                            GroupLayout.Alignment.LEADING,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addComponent(
                                            jPanel5,
                                            GroupLayout.Alignment.LEADING,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                )
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE.toInt())
                        )
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE.toInt())
                .addGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(
                                    jPanel5,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE
                                )
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(
                                    jPanel16,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE
                                )
                                .addContainerGap(12, Short.MAX_VALUE.toInt())
                        )
                )
        )
    } // </editor-fold>                        

    private fun jRadioButton6ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    private fun jRadioButton7ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    private fun jRadioButton28ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    private fun jRadioButton29ActionPerformed(evt: ActionEvent) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify                     
    private var jLabel1: JLabel? = null
    private var jLabel2: JLabel? = null
    private var jLabel3: JLabel? = null
    private var jLabel4: JLabel? = null
    private var jPanel16: JPanel? = null
    private var jPanel5: JPanel? = null
    private var jRadioButton28: JRadioButton? = null
    private var jRadioButton29: JRadioButton? = null
    private var jRadioButton6: JRadioButton? = null
    private var jRadioButton7: JRadioButton? = null // End of variables declaration                   

    /**
     * Creates new form RootWordSearchSettingsJPanel
     * @param searchableTableJPanel
     */
    init {
        initComponents()
    }
}