import java.awt.EventQueue
import kotlin.jvm.JvmStatic
import java.lang.ClassNotFoundException
import java.lang.InstantiationException
import java.lang.IllegalAccessException
import java.util.logging.Level
import java.util.logging.Logger
import javax.swing.*

val alternateSpellingInstructions = "separate alternate search phrases/spellings with \"#\" (e.g. \"phrase1#phrase2\")"

class TabbedJFrame : JFrame() {
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private fun initComponents() {
        jTabbedPane1 = JTabbedPane()
        refreshDatabaseButton = JButton()
        jLabel1 = JLabel()
        jLabel2 = JLabel()
        jLabel3 = JLabel()
        defaultCloseOperation = EXIT_ON_CLOSE
        jTabbedPane1.addTab(
            "Seforim by name",
            (FindSeferByCriteriaJPanel("Enter name of sefer - $alternateSpellingInstructions:") { it.seferName }).initComponents()
        )
        jTabbedPane1.addTab(
            "Seforim by author",
            (FindSeferByCriteriaJPanel("Enter author of sefer - $alternateSpellingInstructions:") { it.author }).initComponents()
        )
        jTabbedPane1.addTab(
            "Seforim by category",
            (FindSeferByCriteriaJPanel("Enter category of sefer - $alternateSpellingInstructions:") { it.category }).initComponents()
        )
        jTabbedPane1.addTab(
            "Authors",
            ListOfAuthorsJPanel().initComponents()
        )
        jTabbedPane1.addTab(
            "Categories",
            ListOfCategoriesJPanel().initComponents()
        )
        refreshDatabaseButton.text = "Refresh Database"
        val programVersion = "1.0.0"
        val getLastUpdateString = { "Database last updated: ${Catalog.lastModificationDate()}"}
        jLabel1.text = "Program version: $programVersion"
        jLabel2.text = getLastUpdateString()
        jLabel3.text = "For tech support, please contact ssternbach@torahdownloads.com; for catalog support, please contact Asher Lewis"

        refreshDatabaseButton.addActionListener {
            Catalog.refreshObjects()
            jLabel2.text = getLastUpdateString()
        }

        val layout = GroupLayout(contentPane)
        contentPane.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(refreshDatabaseButton)
                                        .addPreferredGap(
                                            LayoutStyle.ComponentPlacement.RELATED,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addComponent(jLabel1)
                                )
                                .addComponent(jTabbedPane1)
                                .addGroup(
                                    GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 216, Short.MAX_VALUE.toInt())
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, GroupLayout.Alignment.TRAILING)
                                        )
                                )
                        )
                        .addContainerGap()
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(refreshDatabaseButton)
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                )
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE.toInt())
                        .addContainerGap()
                )
        )
        pack()
    } // </editor-fold>                        

    private lateinit var findSeferByNameJPanel: FindSeferByCriteriaJPanel
    private lateinit var refreshDatabaseButton: JButton
    private lateinit var jLabel1: JLabel
    private lateinit var jLabel2: JLabel
    private lateinit var jLabel3: JLabel
    private lateinit var jTabbedPane1: JTabbedPane

    companion object {
        /**
         * @param args the command line arguments
         */
        @JvmStatic
        fun main(args: Array<String>) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
            try {
                for (info in UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus" == info.name) {
                        UIManager.setLookAndFeel(info.className)
                        break
                    }
                }
            } catch (ex: ClassNotFoundException) {
                Logger.getLogger(TabbedJFrame::class.java.name).log(Level.SEVERE, null, ex)
            } catch (ex: InstantiationException) {
                Logger.getLogger(TabbedJFrame::class.java.name).log(Level.SEVERE, null, ex)
            } catch (ex: IllegalAccessException) {
                Logger.getLogger(TabbedJFrame::class.java.name).log(Level.SEVERE, null, ex)
            } catch (ex: UnsupportedLookAndFeelException) {
                Logger.getLogger(TabbedJFrame::class.java.name).log(Level.SEVERE, null, ex)
            }
            //</editor-fold>

            /* Create and display the form */EventQueue.invokeLater {

                Catalog.initialize()
                TabbedJFrame().isVisible = true
            }
        }
    }

    /**
     * Creates new form TabbedJFrame
     */
    init {
        initComponents()
    }
}