import javax.swing.JPanel
import javax.swing.JTabbedPane
import javax.swing.GroupLayout /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author shmuel
 */
class TabJPanel(val tabs: List<Pair<String, JPanel>>) : JPanel() {
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private fun initComponents() {
        jTabbedPane1 = JTabbedPane()
        for(tab in tabs) jTabbedPane1!!.addTab(tab.first, tab.second)
        val layout = GroupLayout(this)
        this.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE.toInt())
                        .addContainerGap()
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE.toInt())
                        .addContainerGap()
                )
        )
    } // </editor-fold>                        

    // Variables declaration - do not modify                     
    private var jTabbedPane1: JTabbedPane? = null // End of variables declaration

    /**
     * Creates new form TabJPanel
     */
    init {
        initComponents()
    }
}